### ISSUE TITLE
Gem release for rails 5.1

### ISSUE THREAD

**Issue by nbarthelemy** [ActsAsParanoid/acts_as_paranoid#104] opened 2018-05-09 14:32 UTC
Hello -

I am wondering when we can anticipate a gem release for > rails 5.0. We are pulling master into our project, but we need a formally published gem to add to our gemspec. Any help would be greatly appreciated.

Thanks

**Comment by goravbhootra** [comment] 2018-06-03 18:02
Duplicate of https://github.com/ActsAsParanoid/acts_as_paranoid/issues/88

**Closed** 2018-06-04 14:01 UTC
