### ISSUE TITLE
has_many autosave doesn't work on paranoid value 

### ISSUE THREAD

**Issue by shaw3257** [ActsAsParanoid/acts_as_paranoid#68] opened 2017-01-23 18:57 UTC
Hello, 

When modifying a child object on a has_many association, the autosave option allows the child to save when the parent saves. This doesn't seem to work when manually setting the paranoid value because the records are skipped if they're _destroyed_ (https://github.com/rails/rails/blob/master/activerecord/lib/active_record/autosave_association.rb#L397). The problem stems from aliasing `destroyed?` to `deleted?` which uses the changed value when checking if it's `destroyed?` 

Test case exposing the problem : 6697e394082abc2cd71c3b5784c24bcae4dec37a

Any thoughts on solutions?

Let me know if I can help.
Thanks!

**Comment by zzak** [comment] 2017-03-19 14:14
I'm not sure what autosave is doing under the hood, but this test also is wrong because we shouldn't use `send(:paranoid_value)`.

Perhaps autosave was added after all of this?

**Comment by mvz** [comment] 2021-04-24 13:26
@shaw3257 is there a way to reproduce this that does not involve manually setting the `paranoid_value`?

**Comment by mvz** [comment] 2022-05-01 09:38
Closing this since setting `paranoid_value` manually is not supported (the setter is private after all), and no further info was received.

**Closed by mvz** 2022-05-01 09:38 UTC
Labels: more info needed
