### ISSUE TITLE
Default Scope with Paranoia Column Not Applied in Rails 7.2 has_many relations

### ISSUE THREAD

**Issue by navidemad** [ActsAsParanoid/acts_as_paranoid#345] opened 2024-08-14 13:05 UTC
Hi,

Thanks for maintaining this gem.

I'm encountering an issue after upgrading my app from Rails 7.1 to Rails 7.2. Here's what I'm seeing:

Previously in Rails 7.1:
```
Parking.first.to_sql
# => "SELECT * FROM parkings WHERE parkings.deleted IS NULL"

Parking.first.spots.to_sql
# => "SELECT spots.* FROM spots WHERE spots.deleted IS NULL AND spots.parking_id = 1"
```

Now in Rails 7.2:
```
Parking.first.to_sql
# => "SELECT * FROM parkings WHERE parkings.deleted IS NULL"

Parking.first.spots.to_sql
# => "SELECT spots.* FROM spots WHERE spots.parking_id = 1"
```

It seems that when fetching rows from a has_many or has_one association, the default_scope with the paranoia_column is no longer being applied. This change is causing issues in our application.

Is there a way to restore the previous behavior?

Thanks in advance!

**Comment by mvz** [comment] 2024-08-15 06:50
@navidemad I can't seem to reproduce this issue. Can you share some of the table structure and the `acts_as_paranoid` calls?

**Comment by navidemad** [comment] 2024-08-15 10:26
Hi @mvz 

The gem seems to be working fine with a default project as I removed all the unnecessary gems to find out which one was faulty, apparently it comes from the gem "arel_extensions".
I make a reproducible ruby bundle inline script for you:

Create a file called bug.rb with the following content and run it as `ruby bug.rb`

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "pg", "1.5.7"

  # It is working with this version
  # gem "activerecord", "7.1.3.4", require: false
  # It is not working with this version
  gem "activerecord", "7.2.0", require: false
  gem "acts_as_paranoid", "0.10.2", require: false
  gem "arel_extensions", "2.1.11", require: false
end

require "active_record"
require "arel_extensions"

ActiveRecord::Schema.verbose = false
ActiveRecord::Base.logger = nil
ActiveRecord::Base.then do |base|
  base.establish_connection(adapter: "postgresql", host: "localhost", database: "postgres")
  begin
    base.connection.create_database("acts_as_paranoid_bug_report")
  rescue ActiveRecord::DatabaseAlreadyExists
    base.connection.drop_database("acts_as_paranoid_bug_report")
    base.connection.create_database("acts_as_paranoid_bug_report")
  end
  base.establish_connection(adapter: "postgresql", host: "localhost", database: "acts_as_paranoid_bug_report")
end

ActiveRecord::Schema.define do
  create_table :parkings, force: true do |t|
    t.string :name, limit: 255, null: false
    t.datetime :created_at, precision: nil
    t.datetime :updated_at, precision: nil
    t.datetime :deleted_at, precision: nil
  end
  add_index :parkings, :deleted_at

  create_table :spots, force: true do |t|
    t.integer :parking_id, null: false
    t.string :number, limit: 255, null: false
    t.datetime :created_at, precision: nil
    t.datetime :updated_at, precision: nil
    t.datetime :deleted_at, precision: nil
  end
  add_index :spots, :parking_id
  add_index :spots, :deleted_at
end

ActiveRecord::Base.logger = Logger.new($stdout)

require "acts_as_paranoid"
require "minitest/autorun"

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

class Parking < ApplicationRecord
  acts_as_paranoid
  has_many :spots, dependent: :destroy
end

class Spot < ApplicationRecord
  acts_as_paranoid
  belongs_to :parking
end

class BugTest < Minitest::Test
  def setup
    parking = Parking.create!(name: "Foo")
    parking.spots.create!(number: "42")
  end

  def test_output_has_many_relation
    puts ("#" * 100) + Parking.last.spots.to_sql
    assert Parking.last.spots.to_sql.include?("\"spots\".\"deleted_at\" IS NULL")
  end
end
```

**Comment by stackmystack** [comment] 2024-08-19 14:54
I have commented on this issue on our repo, but I think @mvz you should be looking at it as well, since the issue is Relation + the variable that causes the breaking is Rails 7.2 and not arel_extensions, as I explained here https://github.com/Faveod/arel-extensions/issues/114#issuecomment-2296773755.

I'm getting myself more familiar with acts_as_paranoid, but I don't think I will be able to catch it as fast as you guys.

**Comment by mvz** [comment] 2024-08-19 17:44
Thanks for the info @navidemad and @stackmystack, I'll take a look as well to see if I can figure out what's going wrong here.

**Comment by navidemad** [comment] 2024-08-19 20:23
With some bisecting from rails v7.1.3.4 to v7.2.0, i used the following script:

Apparently it starts to fail from this commit:
```
c313d9161360f4539afeb36cc8353ad29ba6bef3 is the first bad commit
commit c313d9161360f4539afeb36cc8353ad29ba6bef3
Author: Rafael Mendonça França <rafael@rubyonrails.org>
Date:   Tue Nov 28 16:59:45 2023 +0000

    Remove deprecated support to pass `rewhere` to `ActiveRecord::Relation#merge`

 activerecord/CHANGELOG.md                          |   4 +
 activerecord/lib/active_record/relation/merger.rb  |  10 +--
 .../lib/active_record/relation/spawn_methods.rb    |  20 +----
 .../lib/active_record/relation/where_clause.rb     |  20 +----
 activerecord/test/cases/relation/merging_test.rb   | 100 ---------------------
 guides/source/7_2_release_notes.md                 |   2 +
 6 files changed, 14 insertions(+), 142 deletions(-)
 ` ` `
 
```ruby
# frozen_string_literal: true

# Usage: ruby <absolute_path/bug.rb> --bisect

require "bundler/inline"
require "open3"

RAILS_REPO_PATH = "/tmp/rails"

# Function to checkout a specific commit in the Rails repository
def checkout_rails_commit(commit)
  system("git clone https://github.com/rails/rails.git #{RAILS_REPO_PATH}") unless Dir.exist?(RAILS_REPO_PATH)
  Dir.chdir(RAILS_REPO_PATH) do
    system("git fetch --all")
    system("git checkout #{commit}")
  end
end

# Function to get the current commit hash and message
def current_commit_info
  Dir.chdir(RAILS_REPO_PATH) do
    commit_hash = `git rev-parse HEAD`.strip
    commit_message = `git log -1 --pretty=%B`.strip
    return commit_hash, commit_message
  end
end

# Function to run the test
def run_test
  Bundler.with_unbundled_env do
    output, _status = Open3.capture2("ruby #{__FILE__} --no-bisect")
    if output.include?("Failure")
      return false
    else
      return true
    end
  end
end

# Function to run git bisect
def bisect
  Dir.chdir(RAILS_REPO_PATH) do
    # Start the bisect process
    system("git bisect start")
    system("git bisect good v7.1.3.4")
    system("git bisect bad v7.2.0")

    # Run the test on each commit during bisect
    system("git bisect run ruby #{__FILE__}")

    # Finish the bisect process and get the result
    system("git bisect reset")
  end
end

# If we are running the bisect process
if ARGV.include?("--bisect")
  bisect
  exit
end

# Main script logic, executed during each bisect step
checkout_rails_commit("HEAD") # Check out the current HEAD or relevant commit

commit_hash, commit_message = current_commit_info
puts "Testing commit #{commit_hash}: #{commit_message}"

gemfile(true) do
  source "https://rubygems.org"

  git_source(:github) { |repo| "https://github.com/#{repo}.git" }

  gem "pg", "1.5.7"

  # Point to the current commit of ActiveRecord from the local Rails repo
  gem "activerecord", path: RAILS_REPO_PATH, require: false
  gem "acts_as_paranoid", "0.10.2", require: false
  gem "arel_extensions", "2.1.11", require: false
end

require "active_record"
require "arel_extensions"

ActiveRecord::Base.logger = nil
ActiveRecord::Schema.verbose = false
ActiveRecord::Base.then do |base|
  base.establish_connection(adapter: "postgresql", host: "localhost", database: "postgres")
  begin
    base.connection.create_database("acts_as_paranoid_bug_report")
  rescue ActiveRecord::DatabaseAlreadyExists
    base.connection.drop_database("acts_as_paranoid_bug_report")
    base.connection.create_database("acts_as_paranoid_bug_report")
  end
  base.establish_connection(adapter: "postgresql", host: "localhost", database: "acts_as_paranoid_bug_report")
end

ActiveRecord::Schema.define do
  create_table :parkings, force: true do |t|
    t.string :name, limit: 255, null: false
    t.datetime :created_at, precision: nil
    t.datetime :updated_at, precision: nil
    t.datetime :deleted_at, precision: nil
  end
  add_index :parkings, :deleted_at

  create_table :spots, force: true do |t|
    t.integer :parking_id, null: false
    t.string :number, limit: 255, null: false
    t.datetime :created_at, precision: nil
    t.datetime :updated_at, precision: nil
    t.datetime :deleted_at, precision: nil
  end
  add_index :spots, :parking_id
  add_index :spots, :deleted_at
end

require "acts_as_paranoid"
require "minitest/autorun"

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

class Parking < ApplicationRecord
  acts_as_paranoid
  has_many :spots, dependent: :destroy
end

class Spot < ApplicationRecord
  acts_as_paranoid
  belongs_to :parking
end

class BugTest < Minitest::Test
  def setup
    parking = Parking.create!(name: "Foo")
    parking.spots.create!(number: "42")
  end

  def test_output_has_many_relation
    assert Parking.last.spots.to_sql.include?("\"spots\".\"deleted_at\" IS NULL")
  end
end

# Execute the test and exit with appropriate status during bisect
exit(run_test ? 0 : 1) if ARGV.include?("--no-bisect")
```

**Comment by mvz** [comment] 2024-08-20 05:39
I've done a `git bisect` on the Rails repository and it tells me this starts breaking at https://github.com/rails/rails/commit/c313d9161360f4539afeb36cc8353ad29ba6bef3. I don't know yet how that change breaks things.

**Comment by mvz** [comment] 2024-08-20 05:42
For reference, here is the version of `bug.rb` that I used for bisecting:

```ruby
# frozen_string_literal: true

require "bundler/inline"

gemfile(true) do
  source "https://rubygems.org"

  gem "sqlite3", "~> 1.7.3"

  gem "activerecord", require: false, path: "./activerecord"
  gem "activesupport", require: false, path: "./activesupport"
  gem "activemodel", require: false, path: "./activemodel"

  gem "acts_as_paranoid", "0.10.2", require: false
  gem "arel_extensions", "2.1.11", require: false
end

require "active_record"
require "arel_extensions"

ActiveRecord::Schema.verbose = false
ActiveRecord::Base.logger = nil
ActiveRecord::Base.then do |base|
  base.establish_connection(adapter: "sqlite3", database: ":memory:")
end

ActiveRecord::Schema.define do
  create_table :parkings, force: true do |t|
    t.string :name, limit: 255, null: false
    t.datetime :created_at, precision: nil
    t.datetime :updated_at, precision: nil
    t.datetime :deleted_at, precision: nil
  end
  add_index :parkings, :deleted_at

  create_table :spots, force: true do |t|
    t.integer :parking_id, null: false
    t.string :number, limit: 255, null: false
    t.datetime :created_at, precision: nil
    t.datetime :updated_at, precision: nil
    t.datetime :deleted_at, precision: nil
  end
  add_index :spots, :parking_id
  add_index :spots, :deleted_at
end

ActiveRecord::Base.logger = Logger.new($stdout)

require "acts_as_paranoid"
require "minitest/autorun"

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

class Parking < ApplicationRecord
  acts_as_paranoid
  has_many :spots, dependent: :destroy
end

class Spot < ApplicationRecord
  acts_as_paranoid
  belongs_to :parking
end

class BugTest < Minitest::Test
  def setup
    parking = Parking.create!(name: "Foo")
    parking.spots.create!(number: "42")
  end

  def test_output_has_many_relation
    puts ("#" * 100) + Parking.last.spots.to_sql
    p Parking.last.spots.where_values_hash
    assert Parking.last.spots.to_sql.include?("\"spots\".\"deleted_at\" IS NULL")
  end
end
```

**Comment by mvz** [comment] 2024-08-20 05:49
Do'h, @navidemad you already did that bisect. Sorry I missed that ...

**Comment by mvz** [comment] 2024-08-20 05:58
I can confirm that reverting that commit on top of the `v7.2.0` tag in the Rails repository fixes this bug.

**Comment by mvz** [comment] 2024-08-20 06:10
This part looks strange to me: https://github.com/rails/rails/commit/c313d9161360f4539afeb36cc8353ad29ba6bef3#diff-2a3cf8f0755b5c5706f693ab23d6953cfec15f5eda8a3f348edede22ccfabf04

The default is `nil`, but the change changes the implementation to the version for when the value is not nil.

The only way that can work is if `predicates_unreferenced_by(other)` and `except_predicates(other.extract_attributes)` do the same thing. My guess is that they do, but `arel_extensions` somehow makes them do different things.

**Comment by mvz** [comment] 2024-08-20 06:58
I foucsed on the new `except_predicats` method, and it contains a call `attrs.include? attr`. With `arel_extensions` that call returns `true`, without it it returns `false`. It boils down to the following two objects being considered equal when `arel_extensions` is present:

```
#<struct Arel::Attributes::Attribute
relation=#<Arel::Table:0x00007fbf1eafef30 @name="spots", @klass=Spot(id: integer, parking_id: integer, number: string, created_at: datetime, updated_at: datetime, deleted_at: datetime), @type_caster=#<ActiveRecord::TypeCaster::Map:0x00007fbf1ec20990 @klass=Spot(id: integer, parking_id: integer, number: string, created_at: datetime, updated_at: datetime, deleted_at: datetime)>, @table_alias=nil>,
name="deleted_at">
#<struct Arel::Attributes::Attribute
relation=#<Arel::Table:0x00007fbf1eafef30 @name="spots", @klass=Spot(id: integer, parking_id: integer, number: string, created_at: datetime, updated_at: datetime, deleted_at: datetime), @type_caster=#<ActiveRecord::TypeCaster::Map:0x00007fbf1ec20990 @klass=Spot(id: integer, parking_id: integer, number: string, created_at: datetime, updated_at: datetime, deleted_at: datetime)>, @table_alias=nil>,
name="parking_id">
```

Clearly, these two objects differ by their `name` property. It looks like `arel_extensions` overrides the equality operator: https://github.com/Faveod/arel-extensions/blob/master/lib/arel_extensions/attributes.rb#L21.

@stackmystack can you take a look at this and tell me what you think?

**Comment by stackmystack** [comment] 2024-08-20 07:12
On it.

**Comment by stackmystack** [comment] 2024-08-20 11:58
@navidemad could you please try this on your main project?

```ruby
  gem 'arel_extensions', git: 'https://github.com/stackmystack/arel-extensions', branch: 'rails-7.2-attributes'
```
  
The issue of `Attribute` equality is indeed from arel-extensions as you noted @mvz.

I'm having a discussion with other maintainers of arel-extensions to make a better decision than the one I did in the suggested branch.

**Comment by stackmystack** [comment] 2024-08-20 12:33
Equality will be deprecated and removed.

**Comment by mvz** [comment] 2024-08-20 13:08
Thanks @stackmystack. Regarding deprecations: I looked at your branch and the deprecation message there, and I hope you can tie the deprecation to an arel_extensions release instead of a Rails release.

**Comment by stackmystack** [comment] 2024-08-20 13:30
> Thanks @stackmystack. Regarding deprecations: I looked at your branch and the deprecation message there, and I hope you can tie the deprecation to an arel_extensions release instead of a Rails release.

We don't have scheduled releases like rails, so we can't promise a depreciation at a specific point in time, or a version number. But maybe you mean conditioning the warning emission on a arel_exteisions version and not that of rails?

**Comment by mvz** [comment] 2024-08-20 15:20
> But maybe the warning message should be clearer and make sure users understand it's a message from arel_extensions.

Yes, that seems important since users could upgrade to a new `arel_extensions` version that drops those methods while staying on the same Rails version.

**Comment by mvz** [comment] 2024-08-21 05:39
I'm going to close this issue because there's nothing to do on the part of acts_as_paranoid.

**Closed by mvz** 2024-08-21 05:39 UTC
