### ISSUE TITLE
Save deleted record failed without throw a meaningful error message

### ISSUE THREAD

**Issue by gamesover** [ActsAsParanoid/acts_as_paranoid#145] opened 2020-01-31 03:21 UTC
We have some records `valid?` but cannot `save` and checking `errors` just got empty array `[]`

After debugging, we found `acts_as_paranoid` prevent saving a deleted record without throw a meaningful error message.

I think it is better to add a meaningful message to help debugging.

**Comment by mvz** [comment] 2020-01-31 08:24
Just to understand the use case a bit better, why do you want to save a soft-deleted record?

**Comment by gamesover** [comment] 2020-01-31 08:27
We deleted the record, but sometimes, we still want to update some fields of deleted records.

**Comment by mvz** [comment] 2020-01-31 09:26
I'm afraid Rails 5.2 and up won't save a record if `#destroyed?` returns true. This was already a known issue for creating records directly in a soft-deleted state, but apparently the same problem exists for existing soft-deleted records.

I suppose we can make `acts_as_paranoid` throw a better message for `#save!` than the current Rails default of "Failed to save the record". Regular `#save` will always just return `false` though, to match the behavior for regular records.

**Comment by gamesover** [comment] 2020-01-31 10:10
ah, sorry, so it sounds it is more than Rails 5.2 issue, rather than `acts_as_paranoid`.

If so, I think it shall Rails 5.2 throw a more meaningful error message rather than `Failed to save the record`.

**Comment by pboling** [comment] 2020-12-19 01:57
I am working on migrating old data to be encrypted using [lockbox](lockbox: Modern encryption for Ruby and Rails), and this issue is preventing me from migrating my data.  This is very problematic, because I have to encrypt the data, even if it has been deleted.

The solution I have found is to use [the `migrate_record` branch of my fork of lockbox](https://github.com/pboling/lockbox/tree/migrate_record) and then to decorate the `migrate_record` method with error handling using my [`debug_logging` gem](https://github.com/pboling/debug_logging/), like so:
```
module Lockbox
  class Migrator
    extend DebugLogging
    include DebugLogging::InstanceLogger.new(
      i_methods: [:migrate_record],
      config: {
        args_to_s_proc: ->(*record) { r = record.flatten.first; "Encrypted #{r.class} id: #{r.id}" },
        error_handler_proc: ->(config, error, _obj, _method_name, args) {
          record = args.first
          if error.class.to_s == "ActiveRecord::RecordNotSaved" && error.message =~ /Failed to save the record/ && record.errors.full_messages == []
            # The record failed due to acts_as_paranoid, and ActiveRecord
            #   https://github.com/ActsAsParanoid/acts_as_paranoid/issues/145
            # So we have to recover the deleted record first, then save it for encrypting, then re-delete it.
            result = record.recover(recursive: false, raise_error: false)
            config.log("Recovered *deleted* #{record.class} id: #{record.id} => #{result}")
            result = record.save!(validate: false)
            config.log("Encrypted *deleted* #{record.class} id: #{record.id} => #{result}")
            record.destroy
            config.log("Re-deleted *deleted* #{record.class} id: #{record.id}")
          else
            config.log("#{error.class}: #{error.message} for #{record.id}\nFull messages: #{record.errors.full_messages}")
            raise error
          end
        },
        logger: Logger.new($stdout)
      }
    )
  end
end
```

Which resulted in the following output:
```
D, [2020-12-19T01:55:21.357771 #10375] DEBUG -- : Lockbox::Migrator#migrate_record(Encrypted Location id: 2) ~47033826247000@342921.3576~ debug: {}
D, [2020-12-19T01:55:21.510972 #10375] DEBUG -- : Lockbox::Migrator#migrate_record(Encrypted Location id: 3) ~47033825479320@342921.5109~ debug: {}
D, [2020-12-19T01:55:21.623836 #10375] DEBUG -- : Lockbox::Migrator#migrate_record(Encrypted Location id: 4) ~47033825215740@342921.6237~ debug: {}
D, [2020-12-19T01:55:21.727191 #10375] DEBUG -- : Lockbox::Migrator#migrate_record(Encrypted Location id: 5) ~47033824976340@342921.7271~ debug: {}
D, [2020-12-19T01:55:21.838606 #10375] DEBUG -- : Lockbox::Migrator#migrate_record(Encrypted Location id: 6) ~47033824693800@342921.8385~ debug: {}
D, [2020-12-19T01:55:22.055671 #10375] DEBUG -- : Recovered *deleted* Location id: 6 => true
D, [2020-12-19T01:55:22.158236 #10375] DEBUG -- : Encrypted *deleted* Location id: 6 => true
D, [2020-12-19T01:55:22.159783 #10375] DEBUG -- : Re-deleted *deleted* Location id: 6
...
```

**Comment by mvz** [comment] 2020-12-19 07:21
If the migration would happen in a regular Rails migration, I would simply recommend creating a separate model class there, without `acts_as_paranoid`. I'm not entirely sure why Lockbox migrates the data outside a Rails migray.

**Comment by pboling** [comment] 2020-12-19 10:24
> I'm not entirely sure why Lockbox migrates the data outside a Rails migration.

During deploys the app is generally offline while migrations run, because normally migrations are schema migrations.  So unless you run the migration in a non-standard manner (I.e. how to get it into production without deploying, or without provisioning a whole new production environment just for the migration?) your app will be off-line the entire time.

When migrating hundreds of gigabytes of data it can take a long time.  One of the best features of lockbox is zero-downtime upgrades to encrypted data.

For my use case, at least, a Rails migration is a non-starter.

**Comment by mvz** [comment] 2020-12-19 11:20
I don't agree that a Rails app is offline generally while migrations run, but that is perhaps not very relevant; a deployment that takes a very long time because gigabytes of data need to be migrated would be problematic regardless.

I would probably create a rake task with a custom model to do the migration in this case.

**Comment by mvz** [comment] 2020-12-19 11:21
In any case, it would be nice to have the option of saving the soft-deleted record for cases like this.

**Comment by pboling** [comment] 2020-12-20 12:21
Rails apps define the active record models based on introspecting the schema when the app boots.  The schema must match the actual columns in the DB or when you attempt to save record you can get errors (missing column, etc).

Yes, rails apps are offline while migrations run.  Sometimes, with backwards compatible schema migrations and a blue/green, or other multi-tier deployment strategy, you can get away with having a live rails app hitting a database that is on a different schema, but that's certainly not always the case.

**Comment by pboling** [comment] 2020-12-20 12:23
The rake task suggestion wouldn't work if you old the environment, because that would load the models.

If you don't load the environment, then you would have to load all kinds of other things, and setup a lot of code to get things configured so records can be saved properly. A large portion of each model may need to be reproduced if you rely on many save callbacks.

**Comment by mvz** [comment] 2020-12-20 13:03
On the contrary, during a data migration you don't want any save callbacks to be run.

For a rake task you would indeed load the entire environment, but you would use a custom model for the data migration, for example:

```
class MyDummyModel
  self.table_name = "the_table"
  encrypts :foo, migrating: true
end

Lockbock.migrate(MyDummyModel)
```

**Comment by pboling** [comment] 2020-12-20 19:24
In many situations that will work, just not in situations that *rely* on save callbacks.  This isn't a basic rails app.  It's a very old, very giant rails app, with many connected things, and when the data changes, including becoming encrypted, it needs to be replicated to other systems, and those sometimes rely on callbacks to enqueue the replication.

Yes everything can be worked around.  I just don't have the time.  My solution works with everything as-is, which is exactly what I needed.  I appreciate that your suggestions would work for other people.

**Comment by pboling** [comment] 2020-12-20 19:29
Also, FWIW, data migrations in standard rails migrations is something I consider a code smell, and would recommend that people never do it.  I'll leave it to the curious to read about why this is.

I'm unsure if you were unaware of this mantra, but it seems to be a widely-held view in the Rails community:

> By definition, Rails migrations should only be used for schema changes and not for actual data changes in the database.
> Generally speaking, manipulating data in migrations is a bad idea for a few reasons.

https://thoughtbot.com/blog/data-migrations-in-rails

**Comment by mvz** [comment] 2020-12-20 19:37
I'm going to close this issue since not being able to save a deleted record is default Rails behavior and it is Rails that produces the error message.

**Closed by mvz** 2020-12-20 19:37 UTC
